name: Test My Action

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:     
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run yarn install
        run: |
          yarn install

      - name: Run bb_action_ci
        uses: arjunbuildbear/test2@21
        with: 
          network: |
            [
              {
                "chainId": 1,
                "blockNumber": 20814270
              },
              {
                "chainId": 137,
                "blockNumber": 63391559
              }
            ]
          deployCmd: "yarn run deploy"
          buildbear_token: "BB"